import "./globals.css";

export const metadata = {
  title: "Routing demo",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="p-8">
        <header className="p-4 bg-blue-400">
          <p>Header</p>
        </header>
        <main>{children}</main>
        <footer className="p-4 bg-gray-400">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
