import "./globals.css";

export const metadata = {
  title: 'Routing demo',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="p-8">{children}</body>
    </html>
  )
}
